---
title: "Milestone_3"
author: "Prachi Naik"
date: "2/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Summary of "Can Violent Protest Change Local Policy Support? Evidence from the Aftermath of the 1992 Los Angeles Riot"

This paper seeks to answer a longstanding question in political science: though violent protests are undoubtedly eye-catching and dramatic, do they actually have an effect on political behavior? Focusing on the 1992 LA "Race Riots" (also commonly called the "Rodney King Riots"), one of the most high profile events of political violence in recent years, Enos and his colleagues found that the riot caused a significant liberal shift in policy support at the polls for issues said to have motivated the riots themselves. Throughout the paper, the researchers use geocoded data analysis to ivestigate the source of this shift and trace it back to the mobilization of African American and Liberal White voters following the LA Riots. The "policy shifts" referenced here are actually local shifts in referendum voting on public goods targeted at urban dwelling racial minorities after the 1992 riots. These policies were put on the ballot before the riots erupted. Though the riot itself was a nonrandom event, the release of the video of police officers brutalizing an unarmed Black man (Rodney King) that ultimately triggered the riot was considered by the researchers to be unrelated to the election timeline. The researchers conducted a difference-in-difference analysis of pre and post riot policy voting to control for secular trends in policy support. They further explored the validity of this causal claim by examining the spatial correlation between how much support for a certain policy changed based on how far from the epicenter of those voters were. Ultimately, they found that the closer voters were to the epicenter of the riots, the more likely they were to vote for policies that provided liberal relief to minority urban communities. 

^[All replication analysis available at: https://github.com/prachiknaik/violent_protest_and_policy_change]

