---
title: "Milestone_4"
author: "Prachi Naik"
date: "2/28/2020"
output: bookdown::pdf_document2
bibliography: bibliography.bib
link_citations: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::write_bib(c("knitr", "stringr"), "bibliography.bib", width = 60)
options(tinytex.verbose = TRUE)

library(tinytex)
library(gt)
library(latexpdf)
library(gtable)
library(bookdown)
library(stargazer)
library(gtsummary)
library(rstanarm)
library(knitcitations)
library(tidyverse)
```

This is my pdf document. Please refer to the Github repository of my final project for further information.^[[Github repository](https://github.com/prachiknaik/violent_protest_and_policy_change)]]


## A Table of Fake Data
```{r fake_data, echo=FALSE}

gender <- rbinom(20, 1, .5)
political_participation <- rnorm(20, .5, .25)
age <- ceiling(rnorm(20, 40, 20))

data = tibble(gender, political_participation, age)


table <- data %>% 
  gt() %>%
  tab_header(
    title = "Political Participation",
    subtitle = "Male and Female Political Participation by Age"
  ) %>%
  fmt_number(columns = vars(political_participation)
             ) %>%
  tab_footnote(footnote = "Political Participation from 0 (not at all participating) to 1 (participating a lot)", locations = cells_column_labels(columns = vars(political_participation))) %>%
  tab_footnote(footnote = "0 = Male, 1 = Female", locations = cells_column_labels(columns = vars(gender))) %>%
  cols_label(
    gender = "Gender",
    political_participation = "Political Participation",
    age = "Age"
    
  ) %>%
  cols_move(vars(age), vars(gender)) %>%
  cols_align("center")

table

#now making a regression out of this

model_1 <- lm(political_participation ~ gender, data = data )
model_2 <- lm(political_participation ~ gender + age, data = data )
```


## Regression Table
```{r, regression table, results= "asis", echo=FALSE}

tbl_regression(
  model_2,
  label = NULL,
  exponentiate = FALSE,
  include = everything(),
  show_single_row = NULL,
  conf.level = NULL,
  intercept = FALSE,
  estimate_fun = NULL,
  pvalue_fun = NULL,
  tidy_fun = NULL,
  show_yesno = NULL,
  exclude = NULL
)
               
```

## References
```{r generated bibliography, echo=FALSE, eval=TRUE, message=FALSE, warning=FALSE}

cleanbib()
options("citation_format"= "pandoc")
read.bibtex(file="bibliography.bib")

#it's not nicely formatted, i don't know how to change that. tried to follow Maria Burzillo's lead but I don't know why I am getting the hastags. I don't understand how she did the references even though I looked at her repo!
```
